### ISSUE TITLE
关于wsl1 的getsocketopt-error

### ISSUE THREAD

**Issue by Autumnhues** [nevermoreluo/bug_trace#1]
[关于wsl1的](https://github.com/nevermoreluo/bug_trace#getsocketopt-error-92-protocol-not-available)
所以wsl1没有其他办法修复这个问题了嘛？

**Comment by nevermoreluo** [comment]
是的，有些接口只有wsl2实现了，https://github.com/microsoft/WSL/issues/1982

**Comment by Autumnhues** [comment]
好的谢谢
